name: Stable Commit

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create empty commit
      run: |
        git config --global user.name 'Kaizerslawten'
        git config --global user.email 'antonio268sic2@gmail.com'
        git commit --allow-empty -m "Empty commit"
        git push
